spring.application.name=oa-system
server.port=8080
spring.datasource.url=JDBC:mysql://localhost:3306/oa_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=${JWT_SECRET:mfZZzMpiUIEGQzpcVS1GcuJL9c2iHyd4eMUXCjElWFc=}
jwt.expiration=7200000